before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
before_script:
  - openssl s_server -pass pass:nope -cert $TRAVIS_BUILD_DIR/nss/tests/files/testcert.pem -accept 1234 -key $TRAVIS_BUILD_DIR/nss/tests/files/privkey.pem -quiet &
script:
  - make test